- name: Add docker group
  group: name=docker

- name: Install docker - install packages
  apt: name={{item}} update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Install docker - add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install docker - use stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: Install docker - install docker
  apt: name=docker-ce update_cache=yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
